
- alias: bthfnOn
  trigger:
    - platform: state
      entity_id: light.hue_white_lamp_1 
      to: "on"
    - platform: state
      entity_id: light.hue_color_lamp_1
      to: "on"  
  action:
    - service: homeassistant.turn_on
      entity_id: switch.intermatic_unknown_type0001_id0003_switch_3
    - service: timer.start
      data:
        entity_id: timer.bath

- alias: bthfnOff
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bath 
  action:
    - service: homeassistant.turn_off
      entity_id: switch.intermatic_unknown_type0001_id0003_switch_3
    - service: homeassistant.turn_off
      entity_id: light.hue_white_lamp_1
    - service: homeassistant.turn_off
      entity_id: light.hue_color_lamp_1

- alias: xmasslightson
  trigger:
    platform: sun
    event: sunset
    offset: "+01:00:00"
  action:
    service: homeassistant.turn_on
    entity_id: switch.tplink88

- alias: xmasslightsoff
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.tplink88

- alias: phonelampoff
  trigger:
    platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    entity_id: light.hue_white_lamp_3

- alias: phonelampon
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: light.hue_white_lamp_3

#- alias: sdhw_on
#  trigger: 
#    platform: time
#    at: '10:00:00'
#  action:
#    - service: homeassistant.turn_on
#      entity_id: switch.tplink63

#- alias: sdhw_off
#  trigger: 
#    platform: time
#    at: '14:00:00'
#  action:
#    - service: homeassistant.turn_off
#      entity_id: switch.tplink63

- alias: ton 
  trigger:
    platform: state
    entity_id: device_tracker.chromecastlr
  action:
    - service: homeassistant.turn_on
      entity_id: switch.intermatic_unknown_type0001_id0003_switch_2
    - service: homeassistant.turn_off
      entity_id: group.plants
    - service: homeassistant.turn_on
      entity_id: switch.intermatic_ha05c_lamp_screw_in_module_switch
    
- alias: TV_off
  trigger:
    - platform: state
      entity_id: device_tracker.chromecastlr
      to: 'not_home'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.intermatic_unknown_type0001_id0003_switch_2
    - delay: 0.01
    - service: homeassistant.turn_on
      entity_id: group.plants
    - delay: 0.01
    - service: homeassistant.turn_off
      entity_id: switch.intermatic_ha05c_lamp_screw_in_module_switch

- alias: cavelight_on
  trigger:
    platform: state
    entity_id: device_tracker.dadpc
    to: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.intermatic_unknown_type0001_id0003_switch
    - service: light.turn_on
      data:
        entity_id: light.hue_white_lamp_1
        brightness: 254
    - service: light.turn_on
      data:
        entity_id: light.hue_color_lamp_1
        brightness: 254
    - service: climate.set_temperature
      data:
        entity_id: climate.thermostat768a85
        temperature: 60
    - service: climate.set_temperature
      data:
        entity_id: climate.thermostat771026
        temperature: 60
    - service: climate.set_temperature
      data:
        entity_id: climate.linear_gctbz48_battery_powered_zwave_thermostat_heating_1 
        temperature: 60

- alias: cavelight_off
  trigger:
    platform: state
    entity_id: device_tracker.dadpc
    to: not_home
  action:
    - service: homeassistant.turn_off
      entity_id: switch.intermatic_unknown_type0001_id0003_switch
    - service: light.turn_off
      data:
        entity_id: light.hue_white_lamp_1
    - service: light.turn_off
      data:
        entity_id: light.hue_color_lamp_1
    - service: climate.set_temperature
      data:
        entity_id: climate.thermostat768a85
        temperature: 71
    - service: climate.set_temperature
      data:
        entity_id: climate.thermostat771026
        temperature: 69
    - service: climate.set_temperature
      data:
        entity_id: climate.linear_gctbz48_battery_powered_zwave_thermostat_heating_1 
        temperature: 69

- alias: N_Hall_light_off
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: light.tp_lb120

- alias: N_Hall_light_on
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    data:
      entity_id: light.tp_lb120
      brightness: 100
      color_temp: 6500

- alias: Send notification of RSS feed title when updated
  trigger:
    platform: event
    event_type: feedreader
  action:
    service: persistent_notification.create
    data_template:
      title: "New HA Podcast available"
      message: "New Podcast available - {{ as_timestamp(now()) | timestamp_custom('%I:%M:%S %p %d%b%Y', true) }}"
      notification_id: "{{ trigger.event.data.title }}"

      
- alias: FrauInOffice
  trigger:
    platform: state
    entity_id: device_tracker.lilly
    to: 'home'
  action:
    service: climate.set_temperature
    entity_id: climate.linear_gctbz48_battery_powered_zwave_thermostat_heating_1
    data:
      temperature: 67
- alias: FrauNotInOffice
  trigger:
    platform: state
    entity_id: device_tracker.lilly
    to: 'not_home'
  action:
    service: climate.set_temperature
    entity_id: climate.linear_gctbz48_battery_powered_zwave_thermostat_heating_1
    data:
      temperature: 60
- alias: MovieTime
  trigger:
    platform: state
    entity_id: device_tracker.lgbigscreen
    to: 'home'
  action:
    service: climate.set_temperature
    entity_id: climate.linear_gctbz48_battery_powered_zwave_thermostat_heating_1
    data:
      temperature: 69
- alias: MovieTimeOver
  trigger:
    platform: state
    entity_id: device_tracker.lgbigscreen
    to: 'not_home'
  action:
    service: climate.set_temperature
    entity_id: climate.linear_gctbz48_battery_powered_zwave_thermostat_heating_1
    data:
      temperature: 60


- alias: plants_on
  trigger:
    platform: time
    at: '06:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: group.plants
    
- alias: plants_off
  trigger:
    platform: time
    at: '22:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.plants

- alias: bson
  trigger:
    platform: state
    entity_id: device_tracker.lgbigscreen
    to: 'home'    
  action:
    - service: homeassistant.turn_on
      entity_id: light.intermatic_ha03wd_lamp_module_level_3
    - service: light.turn_on
      data:
        entity_id: light.hue_white_lamp_2
        brightness: 50
- alias: bsoff
  trigger:
    platform: state
    entity_id: device_tracker.lgbigscreen
    to: 'not_home'    
  action:
    - service: homeassistant.turn_off
      entity_id: light.intermatic_ha03wd_lamp_module_level_3
    - service: light.turn_on
      data:
        entity_id: light.hue_white_lamp_2
        brightness: 254
#- alias: t1
#  trigger:
#    platform: homeassistant
#    event: start
#  action:
#    - service: notify.NOTIFIER_NAME
#      data:
#        title: 'Intruder alert'
#        message: 'Intruder alert at apartment!!'
#- alias: t2
#  trigger:
#    platform: time
#    minutes: '/5'
#    seconds: 00
#  action:
#    - service: notify.NOTIFIER_NAME
#      data:
#        title: 'Intruder alert'
#        message: 'Intruder alert at apartment!!'







