title: My Awesome Home
# Exclude entities from "Unused entities" view
excluded_entities:

views:
    # View tab title.
  - title: Example
    # Optional unique id for direct access /lovelace/${id}
    id: example
    # Each view can have a different theme applied.
    theme: dark-mode
    # The cards to show on this view.
    cards:
      - id: 8f663e7039e14e39a80036c76e33d6aa  # Automatically created id
        type: weather-forecast
        entity: weather.yweather
        # The filter card will filter entities for their state
      - id: 13f9942e016d47a8a6db018ef217f7f7  # Automatically created id
        type: entity-filter
        entities:
          - device_tracker.Mann
          - device_tracker.Frau
        state_filter:
          - home
        card_config:
          type: glance
          title: People that are home

        # The picture entity card will represent an entity with a picture
      - id: 76dab747cd5a4ccd8d32685340e293fa  # Automatically created id
        type: picture-entity
        image: https://www.home-assistant.io/images/default-social.png
        entity: light.c

  - id: 1  # Automatically created id
    icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Second view
    cards:
        # Entities card will take a list of entities and show their state.
      - id: fa93643135a84be8b67c81233fd0072c  # Automatically created id
        type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - light.kitchen
          - switch.ac
          - entity: light.c
            # Override the name to use
            name: Cave light

        # The markdown card will render markdown text.
      - id: de653dcc6b11417f96a8794a570d88a1  # Automatically created id
        type: markdown
        title: Lovelace
        content: >-
          Welcome to your **Lovelace UI**.
