title: Honeylights

views:
  - title: Cameras
    id: cameras
    icons: mdi:camera
    cards:
      - type: picture-entity
        entity: camera.generic_camera
        name: Driveway

  - title: Heat 
    id: Heat
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.thermostat768a85
          - type: thermostat
            entity: climate.thermostat771026
          - type: thermostat
            entity: climate.linear_gctbz48_battery_powered_zwave_thermostat_heating_1
            
  - title: Environment
    id: Environment
    icon: mdi:cloud
    theme: dark-mode
    cards:
      - type: weather-forecast
        entity: weather.yweather
      - type: history-graph
        hours_to_show: 24
        refresh_interval: 300
        entities:
          - sensor.broadlink_sensor_humidity
          - sensor.broadlink_sensor_temperature  
      
  - title: Smartness
    id: smartness 
    icon: mdi:home-assistant
    cards:
      - type: entity-filter
        entities:
          - device_tracker.Mann
          - device_tracker.Frau
        state_filter:
          - home
        card_config:
          type: glance
          title: People that are home
      - type: entities
        entities:
          - entity: zwave.intermatic_ha05c_lamp_screw_in_module_2
            name: SIL2
          - entity: light.tp_lb120
          - entity: light.c
            name: Cave light
          - entity: switch.intermatic_ha05c_lamp_screw_in_module_switch_2
            name: sil2
      - type: entity-filter
        title: What is on?
        entities:
          - light.hue_color_lamp_1
          - light.hue_white_lamp_1
          - light.hue_white_lamp_2
          - light.intermatic_ha03wd_lamp_module_level
          - light.intermatic_ha03wd_lamp_module_level_2
          - light.intermatic_ha03wd_lamp_module_level_4
          - light.intermatic_ha03wd_lamp_module_level_5
        state_filter:
          - "on"
  

